language: python
dist: trusty
# group: edge
before_install:
    sudo apt-get install python-wxgtk2.8
    
    cd /home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages
    # ln -s /usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/ .
    ln -s /usr/lib/python2.7/dist-packages/wx.pth .
    ln -s /usr/lib/python2.7/dist-packages/wxversion.py .
    ln -s /usr/lib/python2.7/dist-packages/wxversion.pyc .
    
    
    ls -al /usr/lib/python2.7/dist-packages/
    ls -al /home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages
  # try to fix dbus error
  # - sudo touch /etc/machine-id
  # - dbus-uuidgen > .myId
  # - sudo cp .myId /etc/machine-id
  # In normal circunstances we would just do "pip install wxPython"
  #- pip install https://wxpython.org/Phoenix/snapshot-builds/linux/gtk3/ubuntu-14.04/wxPython-4.0.0a3.dev3059+4a5c5d9-cp27-cp27mu-linux_x86_64.whl
  # - pip install $WXPACK
install:
  - pip install -r requirements.txt
  # - pip install -r requirements-dev.txt
  - pip install .
# matrix:
  # include:
    # - python: "2.7"
      # env:
        # - WXPACK=https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-14.04/wxPython-4.0.0b2-cp27-cp27mu-linux_x86_64.whl
    # - python: "3.5"
      # env:
        # - WXPACK=https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-14.04/wxPython-4.0.0b2-cp35-cp35m-linux_x86_64.whl
# before_script:
  # - "export DISPLAY=:99.0" 
  # - "sh -e /etc/init.d/xvfb start"
script:
  # - invoke test
  # - invoke --list
  - invoke check-env